### ISSUE TITLE
Scoped service doesn't work on "Development" environment

### ISSUE THREAD

**Issue by Hoshinari55** [Cysharp/ConsoleAppFramework#131]
# Description
When attempting to run the provided console application, an InvalidOperationException is thrown indicating that the scoped service cannot be resolved from the root provider. This issue occurs during the execution of ConsoleApp.Run method where dependency injection is expected to resolve the scoped service.

This error was previously reported in #21 and fixed in #23. However, it appears that the same error has resurfaced. 

# Environment
.NET 8.0.200
ConsoleAppFramework v5.2.1
Microsoft.Extensions.Hosting v8.0.0

# Reproduction code
```
using ConsoleAppFramework;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

var builder = Host.CreateApplicationBuilder(new HostApplicationBuilderSettings { EnvironmentName = "Development" });
builder.Services.AddScoped<IHoge, Hoge>();

using var host = builder.Build();
ConsoleApp.ServiceProvider = host.Services;

ConsoleApp.Run(args, ([FromServices] IHoge hoge) => hoge.Test());

public interface IHoge
{
    public void Test();
}

public class Hoge : IHoge
{
    public void Test()
    {
        Console.WriteLine("Hoge");
    }
}
```

# Expected
```
Hoge
```

# Actual
```
Unhandled exception. System.InvalidOperationException: Cannot resolve scoped service 'IHoge' from root provider.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(ServiceCallSite callSite, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.OnResolve(ServiceCallSite callSite, IServiceScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at ConsoleAppFramework.ConsoleApp.Run(String[] args, Action`1 command) in C:\Workspace\ConsoleAppFrameworkIssue\ConsoleAppFramework\ConsoleAppFramework.ConsoleAppGenerator\ConsoleApp.Run.g.cs:line 42
   at Program.<Main>$(String[] args) in C:\Workspace\ConsoleAppFrameworkIssue\Program.cs:line 11
```

**Comment by neuecc** [comment]
Thanks, It needs to explicitly create a scope.
I think there is a problem with the documentation, so I will revise the documentation to include the following

```csharp
using var host = builder.Build();
using var scope = host.Services.CreateScope();
ConsoleApp.ServiceProvider = scope.ServiceProvider;
```

**Comment by Hoshinari55** [comment]
Thanks for the feedback.!

I have updated the code as you suggested, and it's working as expected. I appreciate your commitment to updating the documentation accordingly. Thank you!
