### ISSUE TITLE
 Fail to match method parameter on XXXX in Swagger

### ISSUE THREAD

**Issue by gitlsl** [Cysharp/ConsoleAppFramework#65]
````
 class Program : ConsoleAppBase // inherit ConsoleAppBase
    {
        static async Task Main(string[] args)
        {
            // target T as ConsoleAppBase.
            await Host.CreateDefaultBuilder(args).RunConsoleAppFrameworkWebHostingAsync("http://localhost:12345");
        }

        // allows void/Task return type, parameter is automatically binded from string[] args.
        public void Run2([Option("n", "name of send user.")] string name, int repeat = 3)
        {
            for (int i = 0; i < repeat; i++)
            {
                Console.WriteLine($"Hello My 2 ConsoleApp from {name}");
            }
        }

      //  [Command("timer")]
        public async Task Timer([Option(0)] uint waitSeconds)
        {
            Console.WriteLine(waitSeconds + " seconds");
            while (waitSeconds != 0)
            {
                // ConsoleAppFramework does not stop immediately on terminate command(Ctrl+C)
                // so you have to pass Context.CancellationToken to async method.
                await Task.Delay(TimeSpan.FromSeconds(1), Context.CancellationToken);
                waitSeconds--;
                Console.WriteLine(waitSeconds + " seconds");
            }
        }
    }
````

when invoke timer  throuth swagger  will show next error
````
fail: ConsoleAppFramework.ConsoleAppEngine[0]
      Fail to match method parameter on Program.Timer. args: Program.Timer -waitSeconds 1
      System.InvalidOperationException: Required argument 0 was not found in specified arguments.
         at ConsoleAppFramework.ConsoleAppEngine.TryGetInvokeArguments(ParameterInfo[] parameters, String[] args, Int32 argsOffset, Object[]& invokeArgs, String& errorMessage)
         at ConsoleAppFramework.ConsoleAppEngine.RunCore(Type type, MethodInfo methodInfo, String[] args, Int32 argsOffset)
````

remove `[Option(0)] ` in method Timer  ,  can solve this problem

q2：how  set response body  when use WebHost

**Comment by neuecc** [comment]
Thanks, 
It's true that WebHosting is in a very constrained state.
It needs to be fixed, but since it is not a high priority, it will not be fixed right now.
