### ISSUE TITLE
Failed to load assembly 'Microsoft.Bcl.AsyncInterfaces' on .NET Core 3.1

### ISSUE THREAD

**Issue by yfakariya** [Cysharp/ConsoleAppFramework#66]
I faced to crash ConsoleAppFramework when it stops its execution.

### Workaround

I can avoid this issue with adding explicit dependency to `Microsoft.Bcl.AsyncInterface` to my app.

### Details

```
Unhandled exception. System.AggregateException: One or more hosted services failed to stop. (Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.  )
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at ConsoleAppFramework.ConsoleAppEngineService.StopAsync(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at ConsoleAppFramework.ConsoleAppEngineService.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)


   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at MYAPP.Program.Main(String[] args)
   at MYAPP.Program.<Main>(String[] args)
```

As long as I investigated this problem, it caused because ConsoleAppFramework indirectly depends on `Microsoft.Bcl.AsyncInterfaces` via `Microsoft.Extensions.Hosting` in `netstandard2.0` and does not provide `netcoreapp3.1`.
When MYAPP uses `netcoreapp3.1`, it ultimately depends on netstandard2.0 `ConsoleAppFramework` which indirectly depends on `Microsoft.Bcl.AsyncInterfaces`, and indirectly depends on **netcoreapp3.1** `Microsoft.Extensions.Hosting` which does not depend on `Microsoft.Bcl.AsyncInterfaces`. So, `Microsoft.Bcl.AsyncInterfaces` is not included in published app binaries because selected `Microsoft.Extensions.Hosting` version does not require it.

### Proposal

I think possible solution is one of following: 
* Add `netcoreapp3.1` version to `ConsoleAppFramework`.
* Add explicit dependency for `Microsoft.Bcl.AsyncInterface` to `netstandard2.0` version of `ConsoleAppFramework`.
* Write about workaround in `Readme.md`.

**Comment by neuecc** [comment]
thanks, I've released `3.3.1` and I adopt `Add netcoreapp3.1 version to ConsoleAppFramework.`.
